baseURL = 'https://www.beatim.co.jp/'
languageCode = 'ja'
title = 'Beatim'
theme = 'ananke'

DefaultContentLanguage = "ja"
# SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.ja]
    title = "Beatim"
    weight = 1
    contentDir = "content/ja"
  # [languages.en]
  #   title = "Beatim Inc."
  #   weight = 2
  #   contentDir = "content/en"

[params]
# トップページのメインイメージへのパス
  mainSections = ["posts"]
#  featured_image = "images/featured-image.jpg"
  date_format = "2006年 1月 2日"
# show_reading_time = true

# サイトの説明
#   description = "ここに企業の概要やサービス内容に関する簡単な説明を入れます。"

# ソーシャルメディアのリンク
#   twitter = "企業のTwitterアカウント"
#   github = "企業のGitHubアカウント"
#   facebook = "企業のFacebookページ"

  text_color = ""
  author = ""
  favicon = "/favicon.ico"
  site_logo = "logo-header.svg"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[menu.main]]
name = "HOME"
url = "/"
weight = 1

[[menu.main]]
name = "SERVICE"
url = "/service/"
weight = 2

[[menu.main]]
name = "NEWS"
url = "/posts/"
weight = 3

[[menu.main]]
name = "CONTACT"
url = "/contact/"
weight = 4

[Author]
name = "株式会社Beatim"
